import $ from 'jquery';
import _ from 'underscore';
import Backbone from 'backbone';

import ContactView from 'app/views/contact_view';

const RolodexView = Backbone.View.extend({
  initialize: function(options) {
    // this.$el is now $('main')

    // Keep track of important sub-elements
    this.listElement = this.$('#contact-cards');
    this.modalElement = this.$('#contact-details');

    // Generate & track Contact Cards (list view)
    this.contactCards = [];
    this.contactTemplate = _.template($('#tmpl-contact-card').html());

    // create contactCards for each Contact (this.model is the Rolodex Collection of Contacts)
    this.model.forEach(function(contact) {
      this.addContactCard(contact);
    }, this);

    // listen for new Contacts in Rolodex. For any: generate new card, re-render view
    this.listenTo(this.model, 'add', this.addContactCard);
    this.listenTo(this.model, 'remove', this.removeContactCard);
    this.listenTo(this.model, 'update', this.render);

    // Keep track of modal element/template
    this.modalSection = this.$('#contact-details');
    this.modalTemplate = _.template($('#tmpl-contact-details').html());
  },

  render: function() {
    // reset list to empty; hide modal
    this.modalSection.hide();
    this.listElement.empty();

    // render each card, add to <ul>
    this.contactCards.forEach(function(card) {
      card.render();

      this.listElement.append(card.$el);
    }, this);

    return this;
  },

  events: {
    'click #contact-details': 'suppressModalHide',
    'click .btn-edit': 'editClick'
  },

  addContactCard: function(contact) {
    // Make new card
    var card = new ContactView({
      model: contact,
      template: this.contactTemplate
    });

    // Listen for any clicks on this card
    this.listenTo(card, 'contact:click', this.showModal);

    // Add card to contactCards array
    this.contactCards.push(card);
  },

  removeContactCard: function(contact) {
    console.log("in removeContactCard. this.contactCards is: " + this.contactCards); // NOTE: log

    this.contactCards = _.reject(this.contactCards, function(card) {
      return card.model == contact;
    });

    console.log("After _.reject, this.contactCards is: " + this.contactCards);
  },

  showModal: function(contact) {
    // console.log('This will SHOW MODAL >--------<'); // NOTE: log
    // console.log(contact); // NOTE: log
    console.log("showModal this.model: " + this.model);
    console.log("showModal this.model.name: " + this.model.name);

    this.contact = contact;

    // set the needed values for template
    var html = this.modalTemplate({
      name: contact.name,
      email: contact.email,
      phone: contact.phone
    });

    // set the modalElement html to the html generated by template & show modal
    this.modalElement.html(html);
    this.modalElement.show();

    console.log("showModal contact.name: " + contact.name);
    console.log("showModal contact: " + contact);

    // this.listenTo(this, 'edit:click', this.editContact); // NOTE: important?!

    return this;
  },

  suppressModalHide: function(event) {
    // prevent click on Modal from bubbling up (which would trigger hideModal)
    event.stopPropagation();
  },

  editClick: function(event) {
    // console.log("Ready to edit! " + this.model); // NOTE: log
    console.log("editClick"); // NOTE: log
    console.log("editClick this" + this); // NOTE: log
    console.log("editClick this.model" + this.model); // NOTE: log
    console.log("editClick this.model.name" + this.model.name); // NOTE: log
    console.log("editClick this.contact " + this.contact); // NOTE: log
    console.log("editClick this.contact.name " + this.contact.name ); // NOTE: log

    this.trigger('edit:click', this.contact);
  }

  // ,
  //
  // editContact: function(contact) {
  //   console.log("editContact!!!"); // NOTE: log
  //   // console.log("this.contact " + this.contact);
  //   console.log("contact " + contact); // NOTE: log
  //   console.log("contact.name " + contact.name); // NOTE: log
  //   // console.log("editContact " + this.contact.name); // NOTE: log
  // }

});

export default RolodexView;
